[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11.2", features = ["macros", "serde"] }
serde = { version = "1.0.210", features = ["derive"] }
slug = "0.1.6"

[lints.clippy]
print_stdout = "deny"
